title: Forge.OS
description: "Forge your strength."
url: "https://heavyc.dev"
baseurl: ""

theme: minima

author:
  name: Heavy C Development Studio, LLC

plugins:
  - jekyll-seo-tag

exclude:
  - PROJECT_SPEC.md
  - VISUAL_SYSTEM.md